export const SET_LOGGED_IN_USER_UUID = 'SET_LOGGED_IN_USER_UUID';
export const UNSET_LOGGED_IN_USER = 'UNSET_LOGGED_IN_USER';
export const SET_LOGGED_IN_USER_PROFILE = 'SET_LOGGED_IN_USER_PROFILE';
export const SET_INVITES = 'SET_INVITES';
